### PR TITLE
V1.3: UI Fixes

### LINKED ISSUE #183: V1.3: UI Recipe Popup Card
Depending on appetite/ability, this can be either in V1.3 or V1.4 (the former is recommended)
Issues to fix:

- [x] Resizing of card to allow scroll for longer recipes
- [x] Displaying of text proper, ensuring that it wraps within the window width without truncating

### PR DESCRIPTION
**Pull request by SeeuSim**
To add:
- [x] Fix UI scaling and scrolling for Recipe Form, Add Form, and Recipe Popup
- [x] Fix horizontal scrolling for Recipe Form, Add Form, and Recipe Popup
- [x] Fix fonts
- [x] Fix labels being truncated
- [x] Add Ingredient, IngredientInfo -> IngredientBuilder converter for edit/add form display, and factor in reverse conversion for saving
- [x] Refactor add/edit forms
- [ ] Fix broken edit form functionality
  - [ ] Unspecific error messages (most errors simply display "At least one field to edit must be provided")
  - [ ] `IllegalArgumentException` not caught when adding an invalid ingredient
  - [x] Steps cannot be edited
  - [ ] Cannot remove a portion or duration
  - [x] Cannot remove an ingredient or step by clearing the field
- [x] Add "enter" keybind to Add/Edit forms to save
  - [ ] "Enter" keybind does not work within ingredient/step text boxes

Closes #183, #184

### CODE REVIEW

File: src/main/java/seedu/recipe/ui/events/EditRecipeEvent.java [hunk 1]
```diff
@@ -16,47 +14,21 @@ public class EditRecipeEvent extends Event {
      */
     public static final EventType<EditRecipeEvent> EDIT_RECIPE_EVENT_TYPE = new EventType<>(Event.ANY, "EDIT_RECIPE");
```
Comment (JamesLiuZX) [inline src/main/java/seedu/recipe/ui/events/EditRecipeEvent.java:15]: While we're at it i'll delete `AddRecipeEvent` and push because it is no longer in use.

File: src/main/resources/view/AddRecipeForm.fxml [hunk 2]
```diff
@@ -12,51 +11,58 @@
...
+    <stylesheets>
+        <URL value="@Form.css"/>
+    </stylesheets>
+    <ScrollPane
+            styleClass="root-layout" hbarPolicy="NEVER"
+            fitToWidth="true" fitToHeight="true"
+            AnchorPane.bottomAnchor="-1.0" AnchorPane.topAnchor="0.0"
+            AnchorPane.leftAnchor="0.0" AnchorPane.rightAnchor="0.0">
+        <VBox xmlns:fx="http://javafx.com/fxml/1" xmlns="http://javafx.com/javafx/8" styleClass="root-box"
+              spacing="8"
```
Comment (JamesLiuZX) [inline src/main/resources/view/AddRecipeForm.fxml:26]: xmlns redundant here since anchorpane already has it

Comment (SeeuSim) [reply src/main/resources/view/AddRecipeForm.fxml]: fixed, removed

File: src/main/java/seedu/recipe/ui/events/EditRecipeEvent.java (hunk 1 above)
Comment (SeeuSim) [reply src/main/java/seedu/recipe/ui/events/EditRecipeEvent.java:15]: fixed, removed

File: src/main/java/seedu/recipe/ui/RecipeCard.java [hunk 3]
```diff
@@ -183,12 +177,12 @@ private void setIngredients(HashMap<Ingredient, IngredientInformation> ingredien
             Entry<Ingredient, IngredientInformation> nextIngredient = entries.next();
             ingredients.add(createUnorderedListItem(
                 IngredientUtil.ingredientKeyValuePairToString(nextIngredient.getKey(), nextIngredient.getValue())
-            ), 0, count);
+                                                   ), 0, count);
             count += 1;
         }
         if (count == 3 && entries.hasNext()) {
```
[the remark this answers is not in the document]
Comment (SeeuSim) [reply src/main/java/seedu/recipe/ui/RecipeCard.java:185]: commented, fixed

**Review by JamesLiuZX — APPROVED** [review]
