### PR TITLE
V1.4: Fix Logic bugs

### LINKED ISSUE #243: V1.4: Logic Fixes
refer to PR body for #245

### PR DESCRIPTION
**Pull request by filbertphang**
Closes #243 #242 #234 #235 #215 #212 #217 #218 #241 #230 #221 #240

Task list (copied from issue):
- [x] `IllegalArgumentException` not caught when adding an invalid ingredient (242, 234)
- [x] More detailed error messages for ingredient parsers (235)
- [x] More detailed error messages in `edit` parsing (215, 212, 217)
- [x] More detailed error messages for `addf` command (218)
- [x] Fix regex parsing for `Name` class and ensure all regexes are documented in UG (241, 230)
- [x] Fix validation for `Portion` (221)
- [x] Fix validation for `Duration` (240)
- [x] Fix removing portions and durations from recipes by emptying the field OR passing in an empty string, e.g. `edit 1 p/ d/`

### CODE REVIEW

File: src/main/java/seedu/recipe/logic/commands/AddFormCommand.java [hunk 1]
```diff
@@ -55,7 +55,7 @@ public CommandResult execute(Model model) throws CommandException {
             model.addRecipe(recipeToAdd);
             return new CommandResult(String.format(MESSAGE_SUCCESS, recipeToAdd.getName()));
         } catch (ParseException e) {
-            throw new CommandException(MESSAGE_PARSE_RECIPE);
+            throw new CommandException(e.getMessage());
```
Comment (JamesLiuZX) [inline src/main/java/seedu/recipe/logic/commands/AddFormCommand.java:58]: Tested with every field because I was worried the message might be too technical for normal users, but the messages are well-done. 
One problem: Invalid input in the `portion` field sometimes returns `unknown command` or has no error message instead of command format error. E.g. inputting `1swag` in `portion `can give `unknown command` or no error message while not adding.

Comment (JamesLiuZX) [reply src/main/java/seedu/recipe/logic/commands/AddFormCommand.java:58]: Same issue occurs in the `name`, `duration` and `portion` fields for `edit form`, except 
deleting the field returns the format error message. E.g. deleting `10.0 minutes` under `duration` returns `A Recipe's duration should consist of an integer/fraction/decimal section and an alphabetic time unit (spaces allowed)`. And `deleting name` should return a more informative message, like 'recipe name cannot be deleted, to delete the recipe, press d on the recipe card.`
No issues on the steps, ingredients and tags though.

Comment (JamesLiuZX) [reply src/main/java/seedu/recipe/logic/commands/AddFormCommand.java:58]: On another note, ps for spamming but "1 serving" does not work also

**Review by SeeuSim — APPROVED** [review]

**Review by JamesLiuZX — APPROVED** [review]
LGTM. 👍

**Review by ZHTang29 — APPROVED** [review]
Good job on fixing the logic and some of the tests, as well as fixing styling and CQ! Overall great effort,  moving forward will add more tests to validate the behavior of recipe classes. LGTM!

**Review by alson001 — APPROVED** [review]
Verified:
#242 #234 fixed
#235 fixed 1,2 entries works and 3,4 shows appropriate error messages.
#215 fixed correct error msg 
#212 error msg: "A Recipe's duration should consist of an integer/fraction/decimal section and an alphabetic time unit (spaces allowed)". A negative integer is submitted for this so idk if the error msg is helpful enough.
#217 fixed #218 fixed #241 fixed
#230 I think it's not the regex fault but the error msg. But this fix may work too if we argue some dishes are named by numbers.
#221 fixed #240 fixed
 Fix removing portions and durations from recipes
